name: "macsima2mc"
description: Staging module transforming MACSima data sets for being registered
  with ASHLAR in MCMICRO, optionally applying illumination correction with
  BaSiCpy.
keywords:
  - imaging
  - ome-tif
  - mcmicro
  - staging
  - spatial-omics
  - macsima
tools:
  - macsima2mc:
      description: "Macsima2mc stages MACSima data sets for being registered with ASHLAR
        in MCMICRO."
      homepage: "https://github.com/SchapiroLabor/macsima2mc"
      documentation: "https://github.com/SchapiroLabor/macsima2mc/README.md"
      tool_dev_url: "https://github.com/SchapiroLabor/macsima2mc"
      licence:
        - "BSD-3-Clause"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - input_dir:
        type: directory
        description: Absolute path to the the parent folder of the raw tiles,
          whose name follows the pattern X_Cycle_N,where N represents the cycle
          number
        pattern: "*Cycle*"
    - output_dir:
        type: string
        description: Absolute path to the directory in which the outputs will be
          saved. If the output directory doesn't exist it will be created.
output:
  out_dir:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - ${output_dir}/*:
          type: directory
          description: |
            Output directory containing subdirectories per well-rack-roi-exp combination.
            Each subdirectory contains a markers.csv table and a raw/ folder with ome.tif files.
          pattern: "*/"
  versions_macsima2mc:
    - - ${task.process}:
          type: string
          description: The name of the process
      - macsima2mc:
          type: string
          description: The name of the tool
      - macsima2mc --version:
          type: eval
          description: The expression to obtain the version of the tool
  versions_basicpy:
    - - ${task.process}:
          type: string
          description: The name of the process
      - basicpy:
          type: string
          description: The name of the tool
      - "python -m pip show basicpy | grep 'Version' | sed -e 's/Version: //g'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - macsima2mc:
          type: string
          description: The name of the tool
      - macsima2mc --version:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - basicpy:
          type: string
          description: The name of the tool
      - "python -m pip show basicpy | grep 'Version' | sed -e 's/Version: //g'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@EfraMP"
  - "@kbestak"
maintainers:
  - "@EfraMP"
  - "@VictorDidier"
