---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_extractpeakprofile"
## TODO nf-core: Add a description of the module and list keywords
description: Extract max intensity peak profile from an image stack with a file of peak coordinates
keywords:
  - image
tools:
  - "bioinfotongli":
      description: "A bioimage analysis toolset of Tong LI"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: 

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1']`
  
  - image:
      type: file
      description: image file
      pattern: "*.{tif/tiff}"

  - peaks:
      type: file
      description: peak location files
      pattern: "*.{csv/tsv/wkt}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1']`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - peak_profile:
      type: file
      description: Peak profile of the entire image stack file
      pattern: "*.npy"

  - peak_locations:
      type: file
      description: Corresponding peak location file
      pattern: "*.csv"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
