---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_mergepeaks"
description: Merge peaks from multiple peak files (csv)
keywords:
  - peaks
  - tiled_analysis
  - imaging 
tools:
  - "bioinfotongli":
      description: "Merge peaks from multiple peak files (csv)"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: MIT
      identifier: 

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
  
    - csvs:
        type: file
        description: csv files containing peaks coordinates
        pattern: "*.csv"
          

## TODO nf-core: Add a description of all of the variables used as output
output:
  - merged_peaks:
    - meta:
        type: file
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - "{output_name}":
        type: file
        description: WKT file
        pattern: "*.wkt"
        ontologies:
          - edam: "http://edamontology.org/operation_Cell_segmentation"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
