---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_concatenatewkts"
description: Concatenate multiple WKT files into one in a brutal way
keywords:
  - wkt
  - segmentation
  - post-processing
tools:
  - "bioinfotongli":
      description: "Concatenate multiple WKT files into one in a brutal way"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: MIT
      identifier: 

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
  
    - wkts:
        type: file
        description: wkts files containing multipoint geometries
        pattern: "*.wkt"

output:
  - concatenated_peaks:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - "${prefix}_merged_peaks.csv":
        type: file
        description: peaks in CSV format
        pattern: "*.csv"
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@BioinfoTongLI"
maintainers:
  - "@BioinfoTongLI"
