---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bioinfotongli_generatetiles"
description: a helper script to generate tiles from an 2D image file
keywords:
  - image
  - tiling
  - slicing
tools:
  - "bioinfotongli":
      description: "A simple script to generate tiles from an 2D image file"
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: MIT
      identifier: 

input:
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`

    - image:
        type: file
        description: raw image to be tiled
        pattern: "*.{tif,ome.tif,ome.tiff}"

output:
  #Only when we have meta
  - - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test' ]`
    - tile_coords:
        type: file
        description: a csv file contains the information of tiles
        pattern: "*.csv"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  

authors:
  - "@BioinfoTongLI"